name: CI workflow

on:
  pull_request:
    branches:
      - "develop"
      - "release_*"

jobs:
  checks:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Install Golang
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: '>=1.22.2'
      - name: Go vet
        run: go vet ./...
  builds:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Install Golang
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: '>=1.22.2'
      - name: Go binary
        run: go build main.go
      - name: Go test
        run: go test ./...

